version: '3'
services:
  apache:
    build: .
    image: winterrific/php-ssmtp:8.1-apache
    volumes:
      - ./www/:/var/www/html/
    expose:
      - 80
    labels:
      - traefik.http.routers.apache-php-ssmtp.rule=Host(`example.com`)
      - traefik.http.routers.apache-php-ssmtp.tls=true
      - traefik.http.routers.apache-php-ssmtp.tls.certresolver=le
      - traefik.http.routers.apache-php-ssmtp.entrypoints=websecure
      - traefik.docker.network=traefik
    environment:
      - SSMTP_HOST
      - SSMTP_PORT
      - SSMTP_FROM_HOSTNAME
      - SSMTP_USE_TLS
      - SSMTP_USE_STARLTLS
      - SSMTP_AUTH_USER
      - SSMTP_AUTH_PASSWORD
      - SSMTP_ROOT
      - SSMTP_DOMAIN

networks:
  traefik:
    external: true
