version: '3'
services:
  apache:
    build: .
    image: winterrific/php-ssmtp:8.1-apache
    volumes:
      - ./www/:/var/www/html/
    expose:
      - 80
    labels:
      - traefik.http.routers.apache-php-ssmtp.rule=Host(`example.com`)
      - traefik.http.routers.apache-php-ssmtp.tls=true
      - traefik.http.routers.apache-php-ssmtp.tls.certresolver=le
      - traefik.http.routers.apache-php-ssmtp.entrypoints=websecure
      - traefik.docker.network=traefik

networks:
  traefik:
    external: true
